spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

jwt.secret=uXJ9hP57oD4Fv5iVm0NfQtkjE8V2uLjKkUeZ9UYyFxA=
jwt.access.expiration=900000
jwt.refresh.expiration=2592000000